### PR TITLE
Fix replacing hash path in various edge cases

### LINKED ISSUE #126: HashtagHistory on Filesystem not working with IE
Hi

This occurs when I open a react website on the filesystem (e.g. index.html) using HashHistory.
##### Firefox, Chrome, Safari
Opening the file `X:\index.html` results in the following:
1. Firefox opens and loads the URL `file:///X:/index.html`
2. The webpage gets loaded fine.
3. The URL gets rewritten to `file:///X:/index.html#/?_crypticid`

##### IE11
Opening the file `X:\index.html` results in the following:
1. IE11 opens and loads the URL `file:///X:/index.html` resp. `X:\index.html`
2. The webpage displays briefly a blank page.
3. The URL gets rewritten to `X:\X:\index.html`
4. IE11 redirects to the IE internal error page "dnserror.html".

In IE11 following messages are shown in the console:
Information: `HTML1300: Navigation occurred.`
Warning: `DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337`

The same site gets loaded just fine in IE, when I use `createMemoryHistory` instead of `createHashtagHistory`.

Any help would be greatly appreciated :)

### PR DESCRIPTION
**Pull request by taion**
Fixes #126

### CODE REVIEW

**Comment by taion** [comment]
Looks like this isn't quite okay on Firefox.

**Comment by taurose** [comment]
Yeah, this reloads when using `<base>` tag that doesn't match current URL ([test](https://github.com/rackt/history/blob/master/modules/__tests__/describeBasename.js#L217)). Fails locally with Chrome, too.

**Comment by mjackson** [comment]
@taurose Just a heads up: There was a lot of discussion in #94 that ultimately led to [removing support for the `<base>` tag](https://github.com/mjackson/history/commit/0cacf4769be583435da4e2e05cd3b2fcc04075dc) entirely. One less thing to worry about :)

**Comment by taurose** [comment]
@mjackson Thanks for letting me know. I had a feeling we were doing something wrong in this regard, but never found time to investigate. [This](https://github.com/mjackson/history/issues/94#issuecomment-204649227) makes a lot of sense.

**Pull request closed without merging**
