### PR TITLE
Specify es2015 modules location with jsnext:main

### PR DESCRIPTION
**Pull request by TrySound**
This will let to use [rollup](https://github.com/rollup/rollup) more efficiently.

### CODE REVIEW

**Comment by TrySound** [comment]
I don't think this error because my change.

**Comment by taion** [comment]
Agreed, going to try to re-run the build to make it pass. Not sure how we forgot to add this when we set up the ES6 build.

**Comment by taion** [comment]
@TrySound Can you rebase?

**Comment by taion** [comment]
I'll take care of it.

**Pull request merged**
