### PR TITLE
Browser history goBack/goForward fix

### PR DESCRIPTION
**Pull request by michalkvasnicak**
Location state was not saved so `getCurrentLocation()` always returned `null` for given `location.key`.

Really don't know if I get it right. :) Should only a key be saved to `window.history.state` as it is, or should whole location be saved instead? Now it is saving key to `window.history.state` and location is saved using `saveState()`.

### CODE REVIEW

**Comment by mjackson** [comment]
@michalkvasnicak Can we get a simple test here, please?

**Comment by michalkvasnicak** [comment]
@mjackson test from test suite was not passing. Now if you allow skipped test for goBack, goForward, it will pass. Is it enough? :)

**Comment by michalkvasnicak** [comment]
This is passing for #6 too (locally in Chrome). HashHistory is still failing.

**Comment by mjackson** [comment]
Superseded by #6, closing.

**Pull request closed without merging**
