### PR TITLE
Add transition middleware

### PR DESCRIPTION
**Pull request by aldendaniels**
#### Status
_WIP_: Working, but needs more tests. Making PR now to get feedback.

#### Overview
This is a PR for the functionality described in #22. This lets users register history middleware that can delay, abort, or redirect transitions programatically. A primary use-case for this is to perform data loading or authentication verification before transitioning to a new route.

The new API adds two new methods:

 - `registerTransitionMiddleware()`
 - `unregisterTransitionMiddleware()`

#### Example
```javascript
function handler(nextLocation, prevLocation, fnNext) {
  fnNext(); // continue;
  // OR
  fnNext(false); // abort
  // OR
  fnNext(createLocation(...)) // redirect.
}

// Register middleware.
let unregister = history.registerTransitionMiddleware(handler);

// Unregister middleware.
unregister() // OR...
history.unregisterTransitionMiddleware(handler); 
```

#### Implementation Details

The middleware will be invoked
 1. When the history object is initially created
 2. On every subsequent transition

Because transitions can now be async, we no longer assert when a new transition interrupts an existing _pending_ transition. Instead, we just silently ignore the interrupted transition.

#### Possible Deprecation
Middleware could replace:

 - the `registerTransitionHook()` method
 - the `unregisterTransitionHook()` method
 - the `getUserConfirmation` option

The functionality to prompt the user can be replaced with:

```javascript
history.registerTransitionMiddleware((ignore1, ignore2, fnNext) => {
  fnNext(confirm('Are you sure?'));
});
```

### CODE REVIEW

**Comment by aldendaniels** [comment]
Right now the middleware is run concurrently, which isn't right. I'll make an update shortly to run the middleware serially in the registered order.

I'd also like for middleware to be able to redirect a transition, instead of just aborting the transition. I need to give a bit more thought to how this should work.

**Comment by aldendaniels** [comment]
Looks like CI tests are failing due to missing BrowserStack credentials.

**Comment by mjackson** [comment]
Hey @aldendaniels! Thanks for submitting this PR. Let's discuss in #22 before moving forward here.

**Comment by mjackson** [comment]
Closing based on the conversation in #22.

**Pull request closed without merging**
