### PR TITLE
Housekeeping updates

### PR DESCRIPTION
**Pull request by taion**
Brings things in sync with https://github.com/rackt/react-router/pull/2492.

### CODE REVIEW

**Comment by taion** [comment]
I dropped the IRC link because, well: https://botbot.me/freenode/rackt/

**Comment by taion** [comment]
The coverage is going to be wrong-ish until https://github.com/caitp/karma-coveralls/pull/30 is released - right now it's just uploading a random browser's coverage instead of merging coverage from all browsers.

**Comment by taion** [comment]
Trying to figure out why the Coveralls status check isn't showing up.

**Comment by taion** [comment]
PEBKAC on my part with the Karma config, obviously. Coveralls check is fixed now. This is good to go.

**Comment by timdorr** [comment]
:+1:

**Pull request merged**
