### PR TITLE
don't strip the hash off of the window path

### PR DESCRIPTION
**Pull request by jeffreywescott**
Without this change, when using `createHistory` or `createBrowserHistory`, the `window.location.hash` gets stripped off of the location, never to be recovered, breaking in-page navigation when using react-router.

### CODE REVIEW

**Comment by ryancbarry** [comment]
:+1:

**Comment by JacobOtte** [comment]
:+1:  This is important stuff.

**Comment by jackmoore** [comment]
This isn't fixed in 1.11.0.  Using history.pushState with a hash strips the hash. Using history.pushState with a hash and a query strips both.

`history.pushState(null, '/home#top')` redirects to `/home`

`history.pushState(null, '/home#top', {page: 2})` also redirects to `/home`

**Comment by janpieterz** [comment]
@mjackson are you aware of this? I'm not a 100% sure but it seems like it indeed still doesn't work (using latest history combined with react-router).

**Comment by zdavis** [comment]
Would be great to see this merged in.

**Comment by zdavis** [comment]
Yes, seems to not be fixed in 1.12.1. I believe the problem is here:

https://github.com/rackt/history/blob/master/modules/createBrowserHistory.js#L70

...Location is being rebuilt without the hash

I'll try to put together a pull request.

**Comment by mjackson** [comment]
Thanks for bringing this to my attention, @jackmoore. I think @zdavis is right about where the problem is. I'll see if I can make a fix.

**Comment by mjackson** [comment]
I should also note that in your second example, @jackmoore, you should be sure you're using the `useQueries` enhancer. That will give you a 3rd `query` arg to `pushState`.

**Comment by mjackson** [comment]
@jackmoore @janpieterz @zdavis This is fixed in 7012f9b697f614c1d412926b04079d6b86732757

**Comment by mjackson** [comment]
Fix released in 1.12.2

**Comment by janpieterz** [comment]
Awesome, thanks a lot for the quick effort!

**Comment by jackmoore** [comment]
@mjackson Thanks, but when I combine the hash with query, it's putting the query in the hash.  I'm using react-router's Link component if that matters.  Am I doing something wrong here?

```
<Link to='/home#top' query={{test: true}}>Test</Link>
```

Redirects to: `/home#top?test=true`

**Comment by zdavis** [comment]
Thanks so much!

**Comment by mjackson** [comment]
@jackmoore That's a slightly separate issue. Let's follow up in https://github.com/rackt/react-router/issues/2176

**Pull request merged**
