### PR TITLE
Remove no-longer-needed CriOS hack

### PR DESCRIPTION
**Pull request by taion**
Fixes https://github.com/rackt/react-router/issues/2565 (again)

### CODE REVIEW

**Comment by mhart** [comment]
Great, thanks for getting on this!

**Comment by steinbachr** [comment]
We love react-router + history! Any idea on when a new build is gonna be rolled? Our iOS + Chrome SPA is hurting a bit since the router is falling back to full page refreshes.

**Comment by taion** [comment]
Hopefully this week some time.

**Comment by steinbachr** [comment]
cool, would be great to be able to roll this into our build

**Pull request merged**
