### PR TITLE
Fail gracefully when security settings prevent access to sessionStorage

### PR DESCRIPTION
**Pull request by masonicboom**
This can happen (at least) in iOS 9 Mobile Safari, when "Block Cookies" is set to "Always Block" (https://github.com/angular-translate/angular-translate/issues/629 suggests this has been true since iOS 7.1.2).

### CODE REVIEW

**Comment by taion** [comment]
This is the same as #99. I think we just want to handle everything in #104.

**Comment by mjackson** [comment]
This is a different error, @taion. #104 is about handling errors when the quota is actually exceeded. This PR is about handling errors when cookies are disabled in a specific environment.

**Comment by taion** [comment]
It's not the same as #104, but it's a more targeted version of the same check as #99, geared toward the same thing. I guess we'd merge these separately and resolve the conflicts later?

**Comment by mjackson** [comment]
Thanks, @masonicboom!

@taion Yes, we'll resolve and merge #104 separately.

**Pull request merged**
