### PR TITLE
Fix `history.push()` and `history.replace()` methods for `useBasename`

### PR DESCRIPTION
**Pull request by th0r**
Fix for #118

### CODE REVIEW

**Comment by knowbody** [comment]
thanks again @th0r 

sorry @mjackson I haven't spotted it last time

**Comment by mjackson** [comment]
The `push` and `replace` methods should not take a 2nd `state` argument. If you need state, use `pushState`.

**Comment by mjackson** [comment]
@knowbody @th0r Can you guys please let me take a look before merging stuff like this? Thanks!

**Comment by knowbody** [comment]
my bad, sorry @mjackson

**Comment by mjackson** [comment]
np. i appreciate your work @knowbody :)

**Pull request merged**
